# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getCorMat <- function(x, rho) {
    .Call(`_bcgpRcpp_getCorMat`, x, rho)
}

rcpp_hello_world <- function() {
    .Call(`_bcgpRcpp_rcpp_hello_world`)
}

