# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Create a correlation matrix
#' 
#' \code{getCorMat} returns a correlation matrix
#' 
#' @param x An \emph{n x d} matrix.
#' @param rho A vector of length d
#' @return An \emph{n x n} correlation matrix
#' @examples
#' n <- 10
#' d <- 2
#' x <- matrix(runif(n * d), ncol = d, nrow = n)
#' rho <- runif(d, 0, 1)
#' getCorMat(x, rho)
#' @export
getCorMat <- function(x, rho) {
    .Call(`_bcgpRcpp_getCorMat`, x, rho)
}

rcpp_hello_world <- function() {
    .Call(`_bcgpRcpp_rcpp_hello_world`)
}

